### ISSUE TITLE
Tasks need to be fulfilled in Project

### ISSUE THREAD

**Issue by chalalala** [chalalala/3D-House-using-OpenGL-and-C-#1]
+ Task: to build an OpenGL application (or game) to demonstrate what you have learned:
- [x] Loading 3D models from files
- [x] Texturing & Coloring
- [x] Illumination, Lighting
- [x] Keyboard and (or) mouse interaction
- [x] Advanced techniques: animation, bump mapping, shader, parametric curve and surface.

**Comment by PhuongPhg** [comment]
For me to rmb:
`git rm -rf --cached .`
